metaDataFormat: "yaml"
disableHugoGeneratorInject: true
baseURL: "https://www.fxsitecompat.dev/"
defaultContentLanguage: "en-ca"
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
disablePathToLower: true
copyright: "Kohei Yoshino and individual contributors."

markup:
  goldmark:
    renderer:
      unsafe: true

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml
  application/opensearchdescription+xml:
    suffixes:
      - xml

outputFormats:
  Atom:
    mediaType: application/atom+xml
  OpenSearch:
    mediaType: application/opensearchdescription+xml

outputs:
  home:
    - "Atom"
    - "HTML"
    - "JSON"
  section:
    - "Atom"
    - "HTML"
    - "JSON"
  taxonomyTerm:
    - "Atom"
    - "HTML"
    - "JSON"
  taxonomy:
    - "Atom"
    - "HTML"
    - "JSON"

taxonomies:
    category: "categories"
    release: "releases"
    status: "statuses"

params:
    Domain: "FxSiteCompat.dev"
    Author:
        Name: "Kohei Yoshino"
        Email: "webmaster@fxsitecompat.dev"
        TwitterUserName: "koyoskeh"
    GoogleSiteSearchID: "006388931142546140887:uidl4-zslfu"

Languages:
    en-ca:
        languageCode: "en-CA"
        languageName: "English"
        weight: 1
        title: "Firefox Site Compatibility"
        Publisher:
            Name: "Firefox Site Compatibility Working Group"
            TwitterUserName: "FxSiteCompat"
        GoogleSiteSearchLangCode: "en"
        FacebookLangCode: "en_US"
        DateFormat:
            Localized: "January 2, 2006"
            ISO8601: "2006-01-02T15:04:05-07:00"
        menu:
            main:
                - name: "Home"
                  weight: 1
                  identifier: "home"
                  url: "/"
                - name: "Blog"
                  weight: 2
                  identifier: "blog"
                  url: "/blog/"
                - name: "Documents"
                  weight: 3
                  identifier: "docs"
                  url: "/docs/"
                - name: "Tools"
                  weight: 4
                  identifier: "tools"
                  url: "/tools/"
                - name: "About"
                  weight: 5
                  identifier: "about"
                  url: "/about/"
                - name: "Contribute"
                  weight: 6
                  identifier: "contribute"
                  url: "/contribute/"
            syndication:
                - name: "Feed"
                  weight: 1
                  identifier: "feed"
                  url: "/index.xml"
            external:
                - name: "Twitter"
                  weight: 1
                  identifier: "twitter"
                  url: "https://twitter.com/FxSiteCompat"
                - name: "GitHub"
                  weight: 2
                  identifier: "github"
                  url: "https://github.com/fxsitecompat"
    ja:
        languageCode: "ja"
        languageName: "日本語"
        weight: 2
        title: "Firefox サイト互換性情報"
        Publisher:
            Name: "Firefox Site Compatibility ワーキンググループ"
            TwitterUserName: "FxSiteCompat"
        GoogleSiteSearchLangCode: "ja"
        FacebookLangCode: "ja_JP"
        DateFormat:
            Localized: "2006 年 1 月 2 日"
            ISO8601: "2006-01-02T15:04:05-07:00"
        menu:
            main:
                - name: "ホーム"
                  weight: 1
                  identifier: "home"
                  url: "/"
                - name: "ブログ"
                  weight: 2
                  identifier: "blog"
                  url: "/blog/"
                - name: "ドキュメント"
                  weight: 3
                  identifier: "docs"
                  url: "/docs/"
                - name: "ツール"
                  weight: 4
                  identifier: "tools"
                  url: "/tools/"
                - name: "概要"
                  weight: 5
                  identifier: "about"
                  url: "/about/"
                - name: "協力"
                  weight: 6
                  identifier: "contribute"
                  url: "/contribute/"
            syndication:
                - name: "フィード"
                  weight: 1
                  identifier: "feed"
                  url: "/index.xml"
            external:
                - name: "Twitter"
                  weight: 1
                  identifier: "twitter"
                  url: "https://twitter.com/FxSiteCompat"
                - name: "GitHub"
                  weight: 2
                  identifier: "github"
                  url: "https://github.com/fxsitecompat"
